### ISSUE TITLE
provide tests 

### ISSUE THREAD

**Issue by marc-portier** [vliz-be-opsci/pykg2tbl#1]
- be sure to check both local ttl loaded into memory as well as external sparql endpoints

**Comment by marc-portier** [comment]
have to also do proper testing of the cli 

test was added as framework (see 10900ba) - but actual assertions are still messing

**Comment by mpo-vliz** [comment]
over time tests have been added 

nothing to do in move to sema.query

over there special attention will be given to good test-coverage
