### ISSUE TITLE
support sparql update statements

### ISSUE THREAD

**Issue by marc-portier** [vliz-be-opsci/pykg2tbl#27]
we currently assume all works, but updating statements in sparql (INSERT / DELETE/ ... ) might not simply work 

things to consider:
- `KGSource.build` might need a separate uri for updating --> reflecting how  [`SPARQLWrapper`](https://sparqlwrapper.readthedocs.io/en/latest/SPARQLWrapper.Wrapper.html#SPARQLWrapper.Wrapper.SPARQLWrapper)  typically expects a distinct `updateEndpoint`
- any authentication required for updates 
- setting the queryType (if needed)

**Comment by mpo-vliz** [comment]
not being transferred to sema.query

as this is now covered in sema.commons.store
