### ISSUE TITLE
cleanup duplicate files

### ISSUE THREAD

**Issue by marc-portier** [vliz-be-opsci/pykg2tbl#3]
striking similarity of contents in 
* [`pykg2tbl/j2/templates`](https://github.com/vliz-be-opsci/pykg2tbl/tree/master/pykg2tbl/j2/templates) vs
* [`tests/sparql_templates`](https://github.com/vliz-be-opsci/pykg2tbl/tree/master/tests/sparql_templates)
most likely this is not needed and should be cleaned

**Comment by mpo-vliz** [comment]
reworded in transfer to sema.query as https://github.com/vliz-be-opsci/py-sema/issues/93
